name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync
      - name: Test
        run: uv run pytest
      - name: Format
        run: uv run ruff format --diff
      - name: Lint
        run: uv run ruff check --output-format=github .
