name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: requirements/test.txt
    - name: Install
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade -r requirements/test.txt
    - name: Test
      run: pytest
    - name: Lint
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
